### ISSUE TITLE
Style improvements on generated components

### ISSUE THREAD

**Issue by bcanfield** [bcanfield/nexquik#15]
I want to keep the styling non-opinionated. So I would like to keep just using vanilla CSS rather than something like Tailwind. 

But it would be nice to base the styling off of something like create-next-app or create-t3-app

**Comment by saulloalmeida** [comment]
* As an idea it might be possible to choose the style of the components in the CLI in the terminal itself with parameters, example: -tailwind -withShadcnUI -otherStyleTemplate 
* Something like DaisyUI already preconfigured?
* Or something more elaborate like a Lib that's been very hot lately, shadcn/ui?
*  Or both?

**Comment by bcanfield** [comment]
That's a great idea!

I like keeping a simple css option and adding more available options, both from a user perspective and a developers perspective.

Some users may want to fully replace the styling, while others may never touch it and just want to get up and running quickly.

And from a developer's side of things, it will be nice and clean to stub out functions and add params.
