### ISSUE TITLE
Circular relationship detected in model

### ISSUE THREAD

**Issue by kubeworkz** [bcanfield/nexquik#57]
I'm getting a message: `Circular relationship detected in model <model name>`. 

Then I get:
```
Generating App Directory
Nexquik Error:
 Error: ENOENT: no such file or directory, scandir '/home/osboxes/.npm/_npx/5799c79029bbfd42/node_modules/nexquik/dist/templateApp/nexquikTemplateModel'
    at Object.readdirSync (node:fs:1527:3)
    at copyDirectory (/home/osboxes/.npm/_npx/5799c79029bbfd42/node_modules/nexquik/dist/helpers.js:29:32)
    at /home/osboxes/.npm/_npx/5799c79029bbfd42/node_modules/nexquik/dist/generators.js:311:45
    at Generator.next (<anonymous>)
    at /home/osboxes/.npm/_npx/5799c79029bbfd42/node_modules/nexquik/dist/generators.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/osboxes/.npm/_npx/5799c79029bbfd42/node_modules/nexquik/dist/generators.js:4:12)
    at generateRoutes (/home/osboxes/.npm/_npx/5799c79029bbfd42/node_modules/nexquik/dist/generators.js:297:20)
    at /home/osboxes/.npm/_npx/5799c79029bbfd42/node_modules/nexquik/dist/generators.js:441:19
    at Generator.next (<anonymous>) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/osboxes/.npm/_npx/5799c79029bbfd42/node_modules/nexquik/dist/templateApp/nexquikTemplateModel'
}
```

Do you know what causes this? Cheers, Dave

**Comment by bcanfield** [comment]
Would you mind sharing your prisma schema?

**Comment by kubeworkz** [comment]
Sure, no problem. It's a bit large...
[saashqsql.tar.gz](https://github.com/bcanfield/nexquik/files/12147578/saashqsql.tar.gz)

Thanks for taking a look.

**Comment by kubeworkz** [comment]
Cool, great idea btw. This is a real time-saver.

**Comment by bcanfield** [comment]
So it looks like there was a casing issue on the directory. Instead of `nexquikTemplateModel`, which it was searching for, it was `nexquiktemplateModel`. 

I pushed up a new version - do a fresh install and see if that worked for you!

**Comment by bcanfield** [comment]
Side note: The circular relation message is just a warning and is perfectly fine.

Since this package recursively tries to create the app, there's just a safe-check in there to prevent it from an infinite loop

**Comment by kubeworkz** [comment]
The circular relationship message came back and I have additional errors:
```
....
Could not find identifier field OR composite type for model: tag_payment
Cannot find identifier field for model: tag_product
Could not find identifier field OR composite type for model: tag_product
Cannot find identifier field for model: tag_proposal
Could not find identifier field OR composite type for model: tag_proposal
Cannot find identifier field for model: tag_request_approval
Could not find identifier field OR composite type for model: tag_request_approval
Cannot find identifier field for model: tag_task
Could not find identifier field OR composite type for model: tag_task
Cannot find identifier field for model: tag_user
Could not find identifier field OR composite type for model: tag_user
....
```

**Comment by bcanfield** [comment]
Ok I am going to use your schema as a test case. Wow that is a big schema

**Comment by kubeworkz** [comment]
yep, it's a lunker. If that one works I think you'll be able to handle anything!

**Comment by bcanfield** [comment]
The main issue is composite primary keys aren't currently supported. 

I'll have to figure out the most graceful way to handle that.

**Comment by kubeworkz** [comment]
Ah, OK. Thanks for digging into this. Definitely putting this in my toolkit.

**Comment by bcanfield** [comment]
Keep an eye on this thread - I'll post when I put in a fix for that. Either tonight or tomorrow.

Thanks again for the helpful debugging info

**Comment by kubeworkz** [comment]
Cool. No problem. In fact, I've carved out some time for this. Anything you need me to do I'm down for it...

**Comment by saashqdev** [comment]
I have a possible business idea that I'd like to run by you which involves your software. Can I email you directly? Cheers, Dave 

btw: rebranded myself to HQ - still same guy....

**Comment by bcanfield** [comment]
Feel free! I just finished adding composite key support last night. Just cleaning up and testing and it should be good to go

**Comment by saashqdev** [comment]
Wicked!

**Comment by saashqdev** [comment]
Were you able to get the schema from hell working?

**Comment by bcanfield** [comment]
I pushed up a new major version with a ton of improvements, including composite keys and a bucket load of other things.

I've been testing with a bunch of large schemas including yours. Let me know if it works out for you.

Thanks again for providing me the schema - it's been extremely helpful. I look forward to hearing back

**Comment by saashqdev** [comment]
Cool, I'll check it out.

**Comment by saashqdev** [comment]
SWEET!
```
Created 38504 files and 28878 directories in 1163.639 seconds.
Created 96 model(s) with a max depth of 5
✔ Success! Enjoy your new app at nexquikApp
File copied to nexquikApp
```
btw: This is the first automation software of _any kind_ to work on this schema - excellent job.

**Comment by bcanfield** [comment]
I tried everything I could to get that time down. It's just... a lot of file IO

**Comment by bcanfield** [comment]
Everything is being done async, but I think there's still some optimization that could be done.
